enum CoffeeMachineType {
  COFFEE_MACHINE_LARGE = 'COFFEE_MACHINE_LARGE',
  COFFEE_MACHINE_SMALL = 'COFFEE_MACHINE_SMALL',
  ESPRESSO_MACHINE = 'ESPRESSO_MACHINE',
}

export default CoffeeMachineType;
